# Generated by Django 4.1.5 on 2024-06-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emp_id',
            field=models.CharField(default='qw', max_length=50),
        ),
    ]
