# Generated by Django 4.1.5 on 2024-06-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_callingdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='callingdetail',
            name='customer_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='callingdetail',
            name='customer_contact_number',
            field=models.IntegerField(default=91),
        ),
        migrations.AddField(
            model_name='callingdetail',
            name='customer_email',
            field=models.EmailField(default='@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='callingdetail',
            name='customer_first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='callingdetail',
            name='customer_last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
