# Generated by Django 4.2.13 on 2024-06-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_callingdetail_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callingdetail',
            name='customer_email',
            field=models.EmailField(default='@gmail.com', max_length=254, unique=True),
        ),
    ]
