# Generated by Django 5.0.7 on 2024-08-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_callingdetail_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_logout',
            field=models.BooleanField(default=False),
        ),
    ]
