# Generated by Django 5.0.7 on 2024-08-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_can_logout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(choices=[('admin', 'Admin'), ('miner', 'Data Miner'), ('agent', 'Calling Agent')], max_length=10),
        ),
    ]
