# Generated by Django 4.1.5 on 2024-06-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiningData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=50)),
                ('clinet_first_name', models.CharField(max_length=50)),
                ('clinet_last_name', models.CharField(max_length=50)),
                ('client_address', models.TextField()),
                ('client_contact_number', models.IntegerField()),
                ('client_mobile_number', models.IntegerField()),
                ('client_email', models.EmailField(max_length=254)),
                ('company_revenue', models.CharField(max_length=50)),
                ('company_emp_size', models.IntegerField()),
                ('client_offering', models.CharField(max_length=30)),
                ('competition_of_AT', models.CharField(max_length=50)),
                ('stock_market_registered', models.CharField(max_length=20)),
                ('influncer', models.BooleanField()),
                ('desition_maker', models.BooleanField()),
                ('IT_spending_budget', models.CharField(max_length=30)),
                ('source_of_data_mining', models.CharField(max_length=50)),
            ],
        ),
    ]
