# Generated by Django 4.1.5 on 2024-06-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miningdata',
            name='date',
            field=models.DateField(default='2024-06-06'),
        ),
    ]
