# Generated by Django 4.1.5 on 2024-06-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tracker', '0002_miningdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miningdata',
            name='date',
            field=models.DateField(default='2024-06-07'),
        ),
    ]
