# Generated by Django 4.1.5 on 2024-06-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tracker', '0003_alter_miningdata_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miningdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='miningdata',
            name='organisation_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
