# Generated by Django 4.1.5 on 2024-06-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tracker', '0004_remove_miningdata_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miningdata',
            name='date',
            field=models.DateField(default='2024-06-10'),
        ),
    ]
