# Generated by Django 4.1.5 on 2024-06-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tracker', '0005_alter_miningdata_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miningdata',
            old_name='client_address',
            new_name='customer_address',
        ),
        migrations.RenameField(
            model_name='miningdata',
            old_name='client_contact_number',
            new_name='customer_contact_number',
        ),
        migrations.RenameField(
            model_name='miningdata',
            old_name='client_email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='miningdata',
            old_name='clinet_first_name',
            new_name='customer_first_name',
        ),
        migrations.RenameField(
            model_name='miningdata',
            old_name='clinet_last_name',
            new_name='customer_last_name',
        ),
        migrations.RenameField(
            model_name='miningdata',
            old_name='client_mobile_number',
            new_name='customer_mobile_number',
        ),
        migrations.RenameField(
            model_name='miningdata',
            old_name='client_offering',
            new_name='customer_offering',
        ),
        migrations.AlterField(
            model_name='miningdata',
            name='date',
            field=models.DateField(default='2024-06-12'),
        ),
    ]
