# Generated by Django 4.1.5 on 2024-06-12 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tracker', '0006_rename_client_address_miningdata_customer_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_datetime', models.DateTimeField(default=datetime.datetime(2024, 6, 12, 10, 13, 54, 846830))),
            ],
        ),
    ]
