# Generated by Django 4.2.13 on 2024-06-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tracker', '0008_delete_timer_alter_miningdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miningdata',
            name='date',
            field=models.DateField(default='2024-06-18'),
        ),
    ]
