# Generated by Django 4.1.5 on 2024-06-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tracker', '0010_alter_miningdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miningdata',
            name='date',
            field=models.DateField(default='2024-06-21'),
        ),
    ]
