# Generated by Django 4.2.13 on 2024-07-08 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tracker', '0012_miningdata_assigned_to_alter_miningdata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.IntegerField()),
                ('job_title', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_tracker.miningdata')),
            ],
        ),
    ]
