# Generated by Django 4.2.13 on 2024-07-10 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales_tracker', '0013_contactdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdata',
            name='assigned_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactdata',
            name='date',
            field=models.DateField(default='2000-10-10'),
        ),
        migrations.CreateModel(
            name='LeadData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254)),
                ('contact_number', models.IntegerField()),
                ('job_title', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('date', models.DateField(default='2000-10-10')),
                ('assigned_to', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contact_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_tracker.contactdata')),
            ],
        ),
    ]
