# Generated by Django 4.2.13 on 2024-07-10 05:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales_tracker', '0014_contactdata_assigned_to_contactdata_date_leaddata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeadData',
            new_name='LeadsData',
        ),
    ]
