# Generated by Django 4.2.13 on 2024-07-10 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales_tracker', '0016_opportunitydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitydata',
            name='sales_stage',
            field=models.CharField(choices=[('prospecting', 'Prospecting'), ('qualification', 'Qualification'), ('needs', 'Needs'), ('value proposition', 'Value Proposition'), ('identifying decision makers', 'Identifying Decision Makers'), ('preception Analysis', 'Perception Analysis'), ('Proposal/price quote', 'Proposal/Prise Quote'), ('negotiation/review', 'Negotiation/Review'), ('closed won', 'Closed Won'), ('closed lost', 'Closed lost')], max_length=50),
        ),
        migrations.CreateModel(
            name='QuotesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('valid_untill', models.DateField()),
                ('approval_status', models.CharField(choices=[('approved', 'Approved'), ('not approved', 'Not Approved')], max_length=50)),
                ('quote_stage', models.CharField(choices=[('draft', 'Draft'), ('negotiation', 'Negotiation'), ('delivered', 'delivered'), ('on hold', 'On Hold'), ('confirmed', 'Confirmed'), ('closed Accepted', 'Closed Accepted'), ('closed lost', 'Closed Lost'), ('closed dead', 'Closed Dead')], max_length=50)),
                ('invoice_status', models.CharField(choices=[('not invoiced', 'Not Invoiced'), ('invoiced', 'Invoiced')], max_length=50)),
                ('approval_issues_description', models.TextField(null=True)),
                ('lead_source', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('billing_address', models.TextField()),
                ('shipping_address', models.TextField()),
                ('total', models.CharField(max_length=50)),
                ('discount', models.CharField(max_length=50)),
                ('sub_total', models.CharField(max_length=50)),
                ('shippting', models.CharField(max_length=50)),
                ('shipptin_tax', models.CharField(max_length=50)),
                ('tax', models.CharField(max_length=50)),
                ('grandtotal', models.CharField(max_length=50)),
                ('date', models.DateField(default='2000-10-10')),
                ('assigned_to', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_tracker.opportunitydata')),
            ],
        ),
    ]
