# Generated by Django 4.2.13 on 2024-07-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tracker', '0018_alter_quotesdata_approval_issues_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotesdata',
            name='approval_issues_description',
            field=models.TextField(null=True),
        ),
    ]
