# Generated by Django 5.0.6 on 2024-07-11 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales_tracker", "0020_alter_quotesdata_approval_issues_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="opportunitydata",
            old_name="lead_sourse",
            new_name="lead_source",
        ),
        migrations.RenameField(
            model_name="quotesdata",
            old_name="shipptin_tax",
            new_name="shipping",
        ),
        migrations.RenameField(
            model_name="quotesdata",
            old_name="shippting",
            new_name="shipping_tax",
        ),
        migrations.RenameField(
            model_name="quotesdata",
            old_name="valid_untill",
            new_name="valid_until",
        ),
    ]
