# Generated by Django 5.0.7 on 2024-08-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tracker', '0021_rename_lead_sourse_opportunitydata_lead_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miningdata',
            name='customer_contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='miningdata',
            name='customer_mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
