# Generated by Django 5.0.7 on 2024-08-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tracker', '0022_alter_miningdata_customer_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
    ]
