# Generated by Django 5.0.7 on 2024-08-14 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tracker', '0024_callingagent_callingagentproxy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='calling_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_tracker.callingagent'),
        ),
    ]
