# Generated by Django 4.2.5 on 2024-08-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_tracker', '0025_alter_contactdata_calling_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdata',
            name='calling_agent',
        ),
    ]
